$schema: https://yourorg.io/schemas/job.v1.json
apiVersion: v1
kind: Job
metadata:
  alias: csv-to-parquet
  labels:
    team: data
trigger:
  type: cron
  configuration:
    cron: "0 * * * *"
    timezone: "America/New_York"
callbacks:
  - type: notification
    configuration:
      webhook_url: "https://hooks.slack.com/services/T000/B000/XYZ"
      channel: "#data-pipelines"
      mention: "@oncall"
steps:
  - name: list
    engine: docker
    image: busybox:1.36
    command: ["sh", "-c", "echo listing s3://demo/csv/*.csv > /out/files.json"]
  - name: convert
    engine: docker
    image: busybox:1.36
    command: ["sh", "-c", "echo converting /in/files.json > /out/manifest.json"]
  - name: publish
    engine: docker
    image: busybox:1.36
    command: ["sh", "-c", "echo publishing /out/manifest.json to s3://demo/parquet/"]
