// Code generated by scripts/generate-metrics-list.go. DO NOT EDIT.
export const PROMETHEUS_METRICS = [
  {
    name: "caesium_auth_key_age_seconds",
    type: "histogram",
    help: "Age of API keys at request time in seconds.",
  },
  {
    name: "caesium_task_cache_entries",
    type: "gauge",
    help: "Current number of task cache entries.",
  },
] as const;
