// Code generated by scripts/generate-metrics-list.go. DO NOT EDIT.
export const PROMETHEUS_METRICS = [
  {
    name: "caesium_job_runs_total",
    type: "counter",
    help: "Total number of job runs by status.",
  },
  {
    name: "caesium_job_run_duration_seconds",
    type: "histogram",
    help: "Duration of job runs in seconds.",
  },
  {
    name: "caesium_task_runs_total",
    type: "counter",
    help: "Total number of task runs by status.",
  },
  {
    name: "caesium_task_run_duration_seconds",
    type: "histogram",
    help: "Duration of task runs in seconds.",
  },
  {
    name: "caesium_jobs_active",
    type: "gauge",
    help: "Number of currently running jobs.",
  },
  {
    name: "caesium_callback_runs_total",
    type: "counter",
    help: "Total number of callback executions by status.",
  },
  {
    name: "caesium_trigger_fires_total",
    type: "counter",
    help: "Total number of trigger fires by type.",
  },
  {
    name: "caesium_worker_claims_total",
    type: "counter",
    help: "Total number of tasks successfully claimed by worker node.",
  },
  {
    name: "caesium_worker_claim_contention_total",
    type: "counter",
    help: "Total number of worker claim contention events.",
  },
  {
    name: "caesium_worker_lease_expirations_total",
    type: "counter",
    help: "Total number of expired worker task leases reclaimed by node.",
  },
  {
    name: "caesium_task_retries_total",
    type: "counter",
    help: "Total number of task retry attempts.",
  },
  {
    name: "caesium_backfill_runs_total",
    type: "counter",
    help: "Total number of runs spawned by backfills by status.",
  },
  {
    name: "caesium_backfills_active",
    type: "gauge",
    help: "Number of currently running backfills.",
  },
  {
    name: "caesium_task_cache_hits_total",
    type: "counter",
    help: "Total number of task cache hits.",
  },
  {
    name: "caesium_task_cache_misses_total",
    type: "counter",
    help: "Total number of task cache misses.",
  },
  {
    name: "caesium_task_cache_entries",
    type: "gauge",
    help: "Current number of task cache entries.",
  },
  {
    name: "caesium_auth_requests_total",
    type: "counter",
    help: "Total authenticated API requests by outcome, role, method, and path.",
  },
  {
    name: "caesium_auth_failures_total",
    type: "counter",
    help: "Total authentication failures by reason.",
  },
  {
    name: "caesium_auth_key_age_seconds",
    type: "histogram",
    help: "Age of API keys at request time in seconds.",
  },
  {
    name: "caesium_audit_log_entries_total",
    type: "counter",
    help: "Total audit log entries by action and outcome.",
  },
  {
    name: "caesium_webhook_auth_failures_total",
    type: "counter",
    help: "Total webhook authentication failures by trigger path and reason.",
  },
] as const;
