package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"strings"
)

func main() {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, "internal/metrics/metrics.go", nil, 0)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing metrics.go: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("// Code generated by scripts/generate-metrics-list.go. DO NOT EDIT.")
	fmt.Println("export const PROMETHEUS_METRICS = [")

	for _, decl := range node.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.VAR {
			continue
		}

		for _, spec := range genDecl.Specs {
			valSpec, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}
			
			if len(valSpec.Values) == 0 {
				continue
			}

			callExpr, ok := valSpec.Values[0].(*ast.CallExpr)
			if !ok {
				continue
			}

			selExpr, ok := callExpr.Fun.(*ast.SelectorExpr)
			if !ok {
				continue
			}

			if selExpr.Sel.Name != "NewCounterVec" && 
				selExpr.Sel.Name != "NewHistogramVec" && 
				selExpr.Sel.Name != "NewGaugeVec" && 
				selExpr.Sel.Name != "NewCounter" && 
				selExpr.Sel.Name != "NewGauge" && 
				selExpr.Sel.Name != "NewHistogram" {
				continue
			}

			mType := "unknown"
			if strings.Contains(selExpr.Sel.Name, "Counter") {
				mType = "counter"
			} else if strings.Contains(selExpr.Sel.Name, "Histogram") {
				mType = "histogram"
			} else if strings.Contains(selExpr.Sel.Name, "Gauge") {
				mType = "gauge"
			}

			if len(callExpr.Args) == 0 {
				continue
			}

			compLit, ok := callExpr.Args[0].(*ast.CompositeLit)
			if !ok {
				continue
			}

			var name, help string
			for _, elt := range compLit.Elts {
				kv, ok := elt.(*ast.KeyValueExpr)
				if !ok {
					continue
				}
				key, ok := kv.Key.(*ast.Ident)
				if !ok {
					continue
				}
				valLit, ok := kv.Value.(*ast.BasicLit)
				if !ok {
					continue
				}
				if key.Name == "Name" {
					name = strings.Trim(valLit.Value, "\"")
				} else if key.Name == "Help" {
					help = strings.Trim(valLit.Value, "\"")
				}
			}

			if name != "" && help != "" {
				fmt.Printf("  {\n")
				fmt.Printf("    name: %q,\n", name)
				fmt.Printf("    type: %q,\n", mType)
				fmt.Printf("    help: %q,\n", help)
				fmt.Printf("  },\n")
			}
		}
	}

	fmt.Println("] as const;")
}
