package main

import (
	"fmt"
	"os"

	"github.com/caesium-cloud/caesium/internal/metrics"
	"github.com/prometheus/client_golang/prometheus"
	dto "github.com/prometheus/client_model/go"
)

func main() {
	metrics.Register()
	
	// Create a new registry for just our metrics to avoid getting standard go metrics
	reg := prometheus.NewRegistry()
	
	// Register our metrics to the new registry
	reg.MustRegister(
		metrics.JobRunsTotal,
		metrics.JobRunDurationSeconds,
		metrics.TaskRunsTotal,
		metrics.TaskRunDurationSeconds,
		metrics.JobsActive,
		metrics.CallbackRunsTotal,
		metrics.TriggerFiresTotal,
		metrics.WorkerClaimsTotal,
		metrics.WorkerClaimContentionTotal,
		metrics.WorkerLeaseExpirationsTotal,
		metrics.TaskRetriesTotal,
		metrics.BackfillRunsTotal,
		metrics.BackfillsActive,
		metrics.TaskCacheHitsTotal,
		metrics.TaskCacheMissesTotal,
		metrics.TaskCacheEntries,
		metrics.AuthRequestsTotal,
		metrics.AuthFailuresTotal,
		metrics.AuthKeyAgeSeconds,
		metrics.AuditLogEntriesTotal,
		metrics.WebhookAuthFailuresTotal,
	)

	mfs, err := reg.Gather()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error gathering metrics: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("// Code generated by scripts/generate-metrics-list.go. DO NOT EDIT.")
	fmt.Println("export const PROMETHEUS_METRICS = [")

	for _, mf := range mfs {
		name := mf.GetName()
		help := mf.GetHelp()
		
		// Map type
		mType := "gauge"
		switch mf.GetType() {
		case dto.MetricType_COUNTER:
			mType = "counter"
		case dto.MetricType_HISTOGRAM:
			mType = "histogram"
		case dto.MetricType_SUMMARY:
			mType = "summary"
		}

		fmt.Printf("  {\n")
		fmt.Printf("    name: %q,\n", name)
		fmt.Printf("    type: %q,\n", mType)
		fmt.Printf("    help: %q,\n", help)
		fmt.Printf("  },\n")
	}

	fmt.Println("] as const;")
}
